# Orb 'circleci/welcome-orb@0.4.1' resolved to 'circleci/welcome-orb@0.4.1'
version: 2
jobs:
  install:
    docker:
    - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
            keys: 
                - {{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}
                - {{ .Environment.CACHE_VERSION }}-dependencies-
        - run:
            command: yarn global add node-gyp && yarn install
            name: yarnCmdTP
        - run:
            command: echo $CACHE_VERSION
            name: cacheVer
        - save_cache:
            paths:
                - node_modules
            key: {{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}

workflows:
  welcome:
    jobs:
    - mybuild
  version: 2