# Orb 'circleci/welcome-orb@0.4.1' resolved to 'circleci/welcome-orb@0.4.1'
version: 2
jobs:
  mybuild:
    docker:
    - image: circleci/node:dubnium
    steps:
        - run:
            command: yarn global add node-gyp && yarn install
            name: yarnCmdTP
        - restore_cache:
            keys: mycache-{{ checksum "package.json" }}
        - run:
            command: echo $CACHE_VERSION
            name: cacheVer
        - save_cache:
            key: mycache-{{ checksum "package.json" }}
            paths:
                - cache/bundle
workflows:
  welcome:
    jobs:
    - mybuild
  version: 2