jobs:
  install:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
            - dependencies-
      - run:
          command: yarn global add node-gyp && yarn install
          name: yarnCmdTP
      - run:
          command: echo $CACHE_VERSION
          name: cacheVer
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
            - dependencies-
      - run:
          name: yarn_lint
          command: yarn lint
      - run:
          name: yarn_format
          command: yarn format:check
  unit_test:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
            - dependencies-
      - run:
          name: yarn_test_ci
          command: yarn test:ci
  set_postgre:
    working_directory: ~/repo
    docker:
      - image: circleci/node:dubnium
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: toto
          POSTGRES_DB: bdtest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
            - dependencies-
      - run:
          name: cmd_test_postgre
          command: yarn test:e2e
          environment:
            POSTGRES_USER: toto
            POSTGRES_DB: bdtest
            JWT_SECRET: "hello world"
            API_PORT: 3000
            API_HOST: localhost
            API_PROTOCOL: http
            DATABASE_URL: postgres://root@localhost:5432/psdb
workflows:
  version: 2
  install_n_build_n_test_n_postgre:
    jobs:
      - install
      - lint:
          requires:
            - install
      - unit_test:
          requires:
            - install
      - set_postgre:
          requires:
            - install
