# Orb 'circleci/welcome-orb@0.4.1' resolved to 'circleci/welcome-orb@0.4.1'
version: 2
jobs:
  mybuild:
    docker:
    - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
        - restore_cache:
            keys: 
                - $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
                - $CACHE_VERSION-dependencies-
        - run:
            command: yarn global add node-gyp && yarn install
            name: yarnCmdTP
        - run:
            command: echo $CACHE_VERSION
            name: cacheVer
        - save_cache:
            key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
            paths:
                - node_modules
workflows:
  welcome:
    jobs:
    - mybuild
  version: 2