# Orb 'circleci/welcome-orb@0.4.1' resolved to 'circleci/welcome-orb@0.4.1'
version: 2
jobs:
  mtbuild:
    docker:
    - image: circleci/yarn
    steps:
    - run:
        command: yarn global add node-gyp && yarn install
        name: yarnCmdTP
workflows:
  welcome:
    jobs:
    - mybuild
  version: 2