jobs:
  install:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
            - dependencies-
      - run:
          command: yarn global add node-gyp && yarn install
          name: yarnCmdTP
      - run:
          command: echo $CACHE_VERSION
          name: cacheVer
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
            - dependencies-
      - run:
          name: yarn_lint
          command: yarn lint
      - run:
          name: yarn_format
          command: yarn format:check
  unit_test:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
            - dependencies-
      - run:
          name: yarn_test_ci
          command: yarn test:ci
  set_postgre:
    docker:
      - image: postgres:9.6-jessie
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
          POSTGRES_PASSWD: toto
          DATABASE_URL: postgres://{{.Environment.POSTGRES_USER}}:{{.Environment.POSTGRES_PASSWD}}@{{.Environment.API_HOST}}:{{.Environment.API_PORT}}/psdb
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
            - dependencies-
      - run:
          command: yarn test:e2e
          name: cmd_test_postgre
workflows:
  version: 2
  install_n_build_n_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - unit_test:
          requires:
            - install
      - set_postgre:
          requires:
            - install
